#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libdbus-c++
Version  : 0.9.0
Release  : 4
URL      : https://ufpr.dl.sourceforge.net/project/dbus-cplusplus/dbus-c%2B%2B/0.9.0/libdbus-c%2B%2B-0.9.0.tar.gz
Source0  : https://ufpr.dl.sourceforge.net/project/dbus-cplusplus/dbus-c%2B%2B/0.9.0/libdbus-c%2B%2B-0.9.0.tar.gz
Summary  : Native C++ bindings for D-Bus (Ecore Mainloop), Not Installed
Group    : Development/Tools
License  : LGPL-2.1
Requires: libdbus-c++-bin = %{version}-%{release}
Requires: libdbus-c++-lib = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : findutils
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(ecore)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtkmm-2.4)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: disable-threading.patch
Patch2: fix-writechar.patch
Patch3: 0001-Fix-gcc47-patch-maintainer-mode-build-examples.patch

%description
Debugging
---------
To compile debugging code configure the project with the --enable-debug option.
Then at runtime you may export the environment variable "DBUSXX_VERBOSE" to any value.

%package bin
Summary: bin components for the libdbus-c++ package.
Group: Binaries

%description bin
bin components for the libdbus-c++ package.


%package dev
Summary: dev components for the libdbus-c++ package.
Group: Development
Requires: libdbus-c++-lib = %{version}-%{release}
Requires: libdbus-c++-bin = %{version}-%{release}
Provides: libdbus-c++-devel = %{version}-%{release}
Requires: libdbus-c++ = %{version}-%{release}

%description dev
dev components for the libdbus-c++ package.


%package lib
Summary: lib components for the libdbus-c++ package.
Group: Libraries

%description lib
lib components for the libdbus-c++ package.


%package staticdev
Summary: staticdev components for the libdbus-c++ package.
Group: Default
Requires: libdbus-c++-dev = %{version}-%{release}

%description staticdev
staticdev components for the libdbus-c++ package.


%prep
%setup -q -n libdbus-c++-0.9.0
cd %{_builddir}/libdbus-c++-0.9.0
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
## build_prepend content
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599681142
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC"
# -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -fPIC"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#export CCACHE_DISABLE=1
## altflags1 end
##
%define _lto_cflags 1
##
%autogen  --prefix=/usr --enable-static --enable-shared --enable-glib --enable-ecore --disable-maintainer-mode
## make_prepend content
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'configure.ac' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'libtool.m4' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
find . -type f -name 'config.status' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
## make_prepend end
make  %{?_smp_mflags}  V=1 VERBOSE=1


%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1599681142
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dbusxx-introspect
/usr/bin/dbusxx-xml2cpp

%files dev
%defattr(-,root,root,-)
/usr/include/dbus-c++-1/dbus-c++/api.h
/usr/include/dbus-c++-1/dbus-c++/connection.h
/usr/include/dbus-c++-1/dbus-c++/dbus.h
/usr/include/dbus-c++-1/dbus-c++/debug.h
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h
/usr/include/dbus-c++-1/dbus-c++/ecore-integration.h
/usr/include/dbus-c++-1/dbus-c++/error.h
/usr/include/dbus-c++-1/dbus-c++/eventloop-integration.h
/usr/include/dbus-c++-1/dbus-c++/eventloop.h
/usr/include/dbus-c++-1/dbus-c++/glib-integration.h
/usr/include/dbus-c++-1/dbus-c++/interface.h
/usr/include/dbus-c++-1/dbus-c++/introspection.h
/usr/include/dbus-c++-1/dbus-c++/message.h
/usr/include/dbus-c++-1/dbus-c++/object.h
/usr/include/dbus-c++-1/dbus-c++/pendingcall.h
/usr/include/dbus-c++-1/dbus-c++/pipe.h
/usr/include/dbus-c++-1/dbus-c++/property.h
/usr/include/dbus-c++-1/dbus-c++/refptr_impl.h
/usr/include/dbus-c++-1/dbus-c++/server.h
/usr/include/dbus-c++-1/dbus-c++/types.h
/usr/include/dbus-c++-1/dbus-c++/util.h
/usr/lib64/libdbus-c++-1.so
/usr/lib64/libdbus-c++-ecore-1.so
/usr/lib64/libdbus-c++-glib-1.so
/usr/lib64/pkgconfig/dbus-c++-1.pc
/usr/lib64/pkgconfig/dbus-c++-ecore-1.pc
/usr/lib64/pkgconfig/dbus-c++-glib-1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdbus-c++-1.so.0
/usr/lib64/libdbus-c++-1.so.0.0.0
/usr/lib64/libdbus-c++-ecore-1.so.0
/usr/lib64/libdbus-c++-ecore-1.so.0.0.0
/usr/lib64/libdbus-c++-glib-1.so.0
/usr/lib64/libdbus-c++-glib-1.so.0.0.0

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libdbus-c++-1.a
/usr/lib64/libdbus-c++-ecore-1.a
/usr/lib64/libdbus-c++-glib-1.a
